### ISSUE TITLE
macOS system DNS resolver is not fully respected

### ISSUE THREAD

**Issue by tashian** [smallstep/cli#383]
Discovered another bug while working in the lab this week. Here's my setup:
- macOS 10.15.7
- Connecting to a Wireguard network that has its own DNS server
- I added a DNS resolver that works only for the `.lab` domain:

```shell-session
$ sudo su -
$ mkdir -p /etc/resolver
$ cat<<EOF > /etc/resolver/lab
domain lab
nameserver fd98:ae2f:c37a::1
nameserver 10.0.2.1
EOF
```

`scutil --dns` confirms that my resolver is active for the `.lab` domain:

```
resolver #1
  nameserver[0] : 10.20.30.40
  nameserver[1] : 10.20.30.41
  flags    : Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)

... (bunch of mdns resolvers) ...

resolver #8
  domain   : lab
  nameserver[0] : fd98:ae2f:c37a::1
  nameserver[1] : 10.0.2.1
  flags    : Request A records
  reach    : 0x00000003 (Reachable,Transient Connection)
```

I can ping the CA just fine:

```shell-session
$ ping ca.lab
PING ca.lab (10.0.2.1): 56 data bytes
64 bytes from 10.0.2.1: icmp_seq=0 ttl=64 time=5.511 ms
64 bytes from 10.0.2.1: icmp_seq=1 ttl=64 time=6.246 ms
64 bytes from 10.0.2.1: icmp_seq=2 ttl=64 time=5.977 ms
^C
--- ca.lab ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 5.511/5.911/6.246/0.304 ms
```

But when I try to bootstrap my CA, it doesn't respect my resolver settings:

```shell-session
$ step ca bootstrap --ca-url https://ca.lab --fingerprint xxx
error downloading root certificate: client.Root; client GET https://ca.lab/root/xxx failed: Get "https://ca.lab/root/xxx": dial tcp: lookup ca.lab on 10.20.30.40:53: no such host
```

**Comment by tashian** [comment]
https://github.com/golang/go/issues/12524

**Comment by maraino** [comment]
@tashian I think this might be solved if you build `step` with CGO_ENABLED=1

**Comment by tashian** [comment]
@maraino I tried `CGO_ENABLED=1 make` and the resultant binary has the same issue

**Comment by tashian** [comment]
This is definitely an upstream bug. It would be cool if this worked, but maybe not worth using a third-party resolver to fix it.

**Comment by tashian** [comment]
Yes @maraino that works! 

`CGO_ENABLED=1 go build -o bin/step github.com/smallstep/cli/cmd/step` builds a `step` that fixes this issue

**Comment by LecrisUT** [comment]
I think we should add this into the `Makefile` for the time being.

**Comment by dopey** [comment]
I believe the issue here is that we were not building the official homebrew version with CGO enabled. We've since changed that, so going forwards official homebrew releases will have CGO enabled and DNS resolution should work.

The OSX artifacts on our github releases are not built with CGO. Would users prefer that we build those w/ CGO as well? I would assume that most users on OSX are using homebrew and those that aren't are able to build the binary themselves with CGO enabled.

**Comment by logopk** [comment]
@dopey the issue is resolved in the latests builds. Thanks.

I would assume that the prebuild binaries should suffer from the same issue and that would hit anyone who runs them in the same setup in a vpn. So why not build them with CGO enabled?

**Comment by LecrisUT** [comment]
> We've since changed that

@dopey can you elaborate on what was done on homebrew side to enable CGO in the bottles? Last I tried those were still not CGO enabled and I don't see the relevant changes in the formula.

**Comment by LecrisUT** [comment]
Oh my, I didn't realize this earlier, but the [upstream formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/step.rb) does not include the `CGO_OVERRIDE` lines which is actually probably why those changes are not found in homebrew bottles. Those changes are in homebrew_smallstep repository, but for some reason they were never picked up during the PRs.
https://github.com/smallstep/homebrew-smallstep/blob/260a5bc247537857240b9e98d13e38b20ffd8f63/step.rb#L20-L21
@dopey What is the purpose of the homebrew-smallstep repository? As a development tap? The changes do not seem to be mirrored, and maybe it is better to just use the homebrew-core fork to avoid these confusions.

**Comment by dopey** [comment]
Hey @LecrisUT we have a private repo that houses our homebrew templates that are then dynamically updated with each new release. I added the `CGO_OVERRIDE` flag to the template for homebrew-core a while ago, but we just haven't had a release since then.

Originally the point of the homebrew-smallstep tap was that we hadn't yet been included in homebrew-core, and even after we had, having a PR accepted and merged could take a while. We're now included in homebrew-core, and the maintainers are generally very quick about processing new PRs. So, from those standpoints the local tap may be vestigial, but I think that it still makes sense as a development tap.

For example the `CGO_OVERRIDE` change (submitted by you) had been applied to the local tap for some time already. Hopefully folks have had a chance to test that out enough, such that now we can build the official release the same way with more confidence.

**Comment by dopey** [comment]
@logopk I am by no means an expert on CGO, that's more @maraino's wheelhouse. But from a cursory search I can see that compiling with CGO comes with risks. The sections of our code that require CGO are not required by all users (originally it was only the yubikey plugins that are not natively built in - we only recently learned about the DNS issues on OSX), and therefore we were wary of adding a risky dependency for everyone, wholesale. Our thinking was that if folks needed the CGO enabled version, they could build it themselves.

**Comment by LecrisUT** [comment]
> Hopefully folks have had a chance to test that out enough, such that now we can build the official release the same way with more confidence.

Maybe it should be documented and have the name of the formula and `conflicts_with` changed so people can tap to it and test it. Also I think the formulas still implement optional build flags that can be used for local formulas but are not used upstream. Don't know how that interacts with bottles and if we can add brew bot to the dev tap, but those should help make it a proper dev tap so people can test out future changes.

> but we just haven't had a release since then.

How about a revesion PR? Normally the template should check for reversion number and other changes by the upstream community anyway so that can help for now until the next release.

Btw I see other formulas use an if `os.mac` for CGO so that it does not affect linuxbrew. Maybe it should be implemented as such for consistency. And why are all the manual tests added as such in the formula? Couldn't they be included in the makefile as a different test target directly?

**Comment by dopey** [comment]
We'll be doing another release in the next couple of days, so this should sort itself out. 

@maraino can you think of any other reasons not to build our Darwin release packages with CGO enabled?

> And why are all the manual tests added as such in the formula? Couldn't they be included in the makefile as a different test target directly?

I built the homebrew template once a few years ago. At the time, a homebrew maintainer helped me because I had (and still have) no idea what I was doing. The result you see was their recommendation, at the time. If you see anything that can be improved I am very willing to accept PRs. Make a PR to https://github.com/smallstep/homebrew-smallstep, and I'll make sure it gets incorporated in our next homebrew official PR.


> Btw I see other formulas use an if `os.mac` for CGO so that it does not affect linuxbrew. Maybe it should be implemented as such for consistency.

Sure, shoot us a PR! As you probably know, our team is small and we are mostly focused on feature development. The homebrew stuff is mostly automated so we don't really think about it anymore. But we'd be mighty grateful if someone with an eye for this stuff took a look at it and made some recommended updates.
